# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20181127_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='room',
        ),
        migrations.AddField(
            model_name='receipt',
            name='room_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='house.House'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
